### ISSUE TITLE
Adaption to new build system

### ISSUE THREAD

**Issue by gaehler** [gap-packages/carat#14]
I pushed a change with should adapt the Carat interface package to the new build system of CARAT. The Travis tests fail, howewer: CARAT builds, but is not loaded into GAP, nor is there a message of a failed loading. Locally, on my system, it works, of course. Any ideas anyone? @fingolfin ?

**Comment by fingolfin** [comment]
The problem is caused by us using `make -j2` on the server, and your build system changes are not safe for parallel use. This can actually be fixed w/o adding new rule dependencies; I'll submit a PR shortly.
