### ISSUE TITLE
Reducing build log

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/carat#2]
Part of the build log is too verbose - probably unpacking the archive may be made with quiet option? 

This, for example, causes "This log is too long to be displayed. Please reduce the verbosity of your build or download the raw log" message here: https://travis-ci.org/gap-packages/cryst/jobs/339917072)
```
cd tables; if [ !  -d qcatalog ] ; then gunzip -c qcatalog.tar.gz | tar xvf - ; fi
qcatalog/
qcatalog/graph.sh
qcatalog/makepres.sh
qcatalog/data3
qcatalog/data2
qcatalog/translation_HM_symbol
qcatalog/mvnew.sh
qcatalog/t-groups-only-part-1.sh
qcatalog/makenew.sh
qcatalog/data5
qcatalog/dim3/
...
... more and more lines
...
```

**Comment by gaehler** [comment]
This has been done in release 2.2.0 and later.
