### ISSUE TITLE
Setting up Travis and CodeCov

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/carat#3]
This will require alterations of the typical setup we currently use for many packages. It will include downloading and building Carat from http://wwwb.math.rwth-aachen.de/carat/ during the build.

**Comment by gaehler** [comment]
I have published a new release of the Carat package:
- new build system using configure & make interface
- builds with the same GMP library as GAP
- if Carat tarball is missing (e.g. in GitHub clones), fetches it in Aachen
- unpacks qcatalog by default only up to dimension 5 (saves 150 Mb)
- no verbose flag in qcatalog unpacking
- testfiles added

The changed build system requires that the special treatment of Carat is removed from the BuildPackages.sh script

**Comment by gaehler** [comment]
gap-system/gap/issues/#2116

**Comment by gaehler** [comment]
With the new build system, I think Carat would now be ready for Travis and CodeCov. The tarball missing in the GitHub version is automatically fetched in the build process. @alex-konovalov  Can I do anything to make this happen?

**Comment by alex-konovalov** [comment]
Closed in #4 - thanks @fingolfin !
